### ISSUE TITLE
How do I make use of the configurations

### ISSUE THREAD

**Issue by lyssieth** [thexivn/RandomMapTogether#4]
This is my first time ever trying to do anything with PyPlanet, but I wanna configure this plugin to be more fun for me (infinite free skips, lower it to gold/silver instead of at/gold).

**Comment by thexivn** [comment]
you can set this property inside the game inside the admin tools (lover right part of the screen)

![image](https://user-images.githubusercontent.com/17314168/231526745-50302336-851a-4edb-82c6-5a7bd300d1cf.png)

If you can't see this that means you are not admin, to become one you need to set `PYPLANET_OWNER` with your Logi ID (you find it logi in trackmania.io) or copy in chat the command `/claim ...` with the ID printed during pyplanet start-up

**Comment by lyssieth** [comment]
Ah, alright. I'll configure things once I'm on desktop again, then. Thanks for the clarification!

I'm waiting on the screws for my desk to arrive so I can put it back together, heh
